---
name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Check npm version
        run: npm --version

      - name: Build Site
        run: npm run build
        env:
          CI: false

      - name: Create Static Route Fallbacks
        run: |
          mkdir -p dist/demo dist/play dist/sounds dist/live dist/game
          cp dist/index.html dist/demo/index.html
          cp dist/index.html dist/play/index.html
          cp dist/index.html dist/sounds/index.html
          cp dist/index.html dist/live/index.html
          cp dist/index.html dist/game/index.html
          # Create a directory structure for game IDs
          mkdir -p dist/game/placeholder
          cp dist/index.html dist/game/placeholder/index.html
          echo "Created static route fallbacks"
          
  deploy-production:
    needs: build-and-preview
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://chesslink.site
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: dist

      - name: Upload Files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT || 22 }}
          source: "dist/*"
          target: "/var/www/chesslink.site/"
          strip_components: 1
          overwrite: true

      - name: Run Server Commands (Permissions & Restart Nginx)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            echo "Setting ownership and permissions on /var/www/chesslink.site..."
            NGINX_USER=$(ps aux | grep "nginx: worker" | grep -v "grep" | \
              awk '{print $1}' | head -1 || echo "www-data")
            sudo chown -R "$NGINX_USER":"$NGINX_USER" /var/www/chesslink.site || \
              echo "Ownership change failed, continuing..."
            sudo find /var/www/chesslink.site -type d -exec chmod 755 {} \; || \
              echo "Directory permissions failed, continuing..."
            sudo find /var/www/chesslink.site -type f -exec chmod 644 {} \; || \
              echo "File permissions failed, continuing..."
            echo "Testing Nginx configuration..."
            sudo nginx -t || echo "Nginx config test failed, attempting restart anyway..."
            echo "Restarting Nginx..."
            sudo systemctl restart nginx || sudo service nginx restart || \
              sudo /etc/init.d/nginx restart || echo "All nginx restart methods failed"
            echo "Deployment commands finished."
